---
name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: build //...
      - name: Sync Dependencies
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: run //scripts:syncdeps
        if: ${{ GITHUB_ACTOR }} == dependabot-preview
      - name: Test
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: test //...
      - name: autocommit
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply syncdeps changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ GITHUB_ACTOR }} == dependabot-preview
