---
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: build //...
      - name: Test
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: test //...
