---
name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Environment debug
        run: env
      - name: Install bazelisk
        run: |
          wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
          chmod +x /usr/local/bin/bazel
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Build
        run: bazel build //...
      - name: Sync Dependencies
        run: bazel run //scripts:syncdeps
        if: github.actor == 'dependabot-preview[bot]'
      - name: Test
        run: bazel test //...
      - name: autocommit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply syncdeps changes
          file_pattern: vendor/\*
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.actor == 'dependabot-preview[bot]'
