---
name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: build //...
      - name: Test
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: test //...
  syncdeps:
    name: SyncDeps
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Sync Dependencies
        uses: ngalaiko/bazel-action@0.29.0
        with:
          args: run //scripts:syncdeps
      - name: Commit Dependencies
        env:
          GITHUB_EVENT_PATH: $GITHBU
        run: |
          # TODO: we could only run this when the actor is dependabot-preview
          echo "Github event path is $GITHUB_EVENT_PATH"
          ./scripts/commit-syncdeps.sh
