name: Publish release binaries

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install bazelisk
        run: |
          sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
      - name: bazel build
        run: bazel build //...
      - name: Artifact debug
        run: |
          ls -l bazel-bin/
      - name: Upload release binaries
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'bazel-bin/lambda_deploy.zip'
